### ISSUE TITLE
0.2.0 Docker image

### ISSUE THREAD

**Issue by bloche** [hartfordfive/protologbeat#14]
Hey hartfordfive, would you be able to push up the latest release (0.2.0) to your docker hub repo?

**Comment by hartfordfive** [comment]
Hi @bloche, I've built and pushed the latest 0.2.0 image.

**Comment by bloche** [comment]
Great! Thanks for the quick response, much appreciated.

**Comment by hartfordfive** [comment]
Glad this beat has been useful to you!
